language: node_js
sudo: false
node_js:
  - '6'
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
cache:
  directories:
    - node_modules
install:
  - npm install --global npm
  - npm install --global flow-typed
  - npm install --global typings
  - npm install --global yarn
  - npm install
before_script:
  - export CHROME_BIN=/usr/bin/google-chrome
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
